import { Component, OnInit, AfterViewInit, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { CrimeApiService } from '../../services/crime-api.service';
import Chart from 'chart.js/auto';
import * as L from 'leaflet';
import * as d3 from 'd3';

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  isTable?: boolean;
  tableData?: any[];
  tableHeaders?: string[];
  timestamp: string;
  isBlocked?: boolean;
}

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit, AfterViewInit {
  @ViewChild('mapKarnatakaContainer') mapKarnatakaContainer!: ElementRef;
  @ViewChild('mapBengaluruContainer') mapBengaluruContainer!: ElementRef;
  @ViewChild('mapDonutCanvas') mapDonutCanvas!: ElementRef;
  @ViewChild('mapBarCanvas') mapBarCanvas!: ElementRef;
  @ViewChild('mapLineCanvas') mapLineCanvas!: ElementRef;
  @ViewChild('networkContainer') networkContainer!: ElementRef;
  @ViewChild('chartCanvas') chartCanvas!: ElementRef;

  activeModule = 'chatbot';
  officerName = 'Arjun Patil';
  officerBadge = 'KSP-BLR-04821';
  officerRole = 'inspector';
  officerDistrict = 'Bengaluru Urban';
  officerStation = 'Jayanagar PS';
  officerLanguage = 'en';
  chatInput = '';
  chatHistory: ChatMessage[] = [];
  isVoiceRecording = false;
  mapKarnataka!: L.Map;
  mapBengaluru!: L.Map;
  selectedCrimeType = 'all';
  mapLocations: any[] = [];
  donutChartInstance: any = null;
  barChartInstance: any = null;
  lineChartInstance: any = null;
  networkData: any = null;
  offenderSearchId = '';
  networkMetrics = { nodes: 260, connections: 357, groups: 20 };
  searchCrimeId = 'KA-2024-01415';
  caseSummaryText = '';
  caseTimeline: any[] = [];
  caseMetadata = {
    linkedPeople: 'Victims, 3 Suspects, 1 Witness',
    linkedLocations: 'Jayanagar, Bengaluru Central',
    totalEvidence: 15,
    evidenceItems: 15
  };
  auditLogs: any[] = [
    { time: '14:32', log: 'S.I. Arjun Patil accessed Case #221' },
    { time: '14:33', log: 'S.I. Arjun Patil uploaded CCTV data' },
    { time: '14:35', log: 'Forensic Analyst uploaded Fingerprint data' },
    { time: '14:35', log: 'AI Summary generated by S.I. Patil' }
  ];
  chartInstance: any = null;

  constructor(private router: Router, private apiService: CrimeApiService) {}

  ngOnInit() {
    const saved = localStorage.getItem('ksp_officer');
    if (saved) {
      const details = JSON.parse(saved);
      this.officerName = details.name;
      this.officerBadge = details.badge;
      this.officerRole = details.role;
      this.officerDistrict = details.district;
      this.officerStation = details.station;
      this.officerLanguage = details.language;
    }
    this.addSystemGreeting();
  }

  ngAfterViewInit() {}

  switchModule(moduleName: string) {
    if (this.officerRole === 'sub_inspector' && (moduleName === 'network' || moduleName === 'trends')) {
      alert(`Access Denied: Sub-Inspector role cannot access ${moduleName}.`);
      return;
    }
    if (this.officerRole === 'policymaker' && (moduleName === 'network' || moduleName === 'caseSummary')) {
      alert(`Access Denied: Policymaker role is restricted.`);
      return;
    }
    this.activeModule = moduleName;
    setTimeout(() => {
      if (moduleName === 'map') this.initMap();
      else if (moduleName === 'network') this.initNetworkGraph();
      else if (moduleName === 'trends') this.initTrendChart();
      else if (moduleName === 'caseSummary') this.fetchCaseSummary();
    }, 100);
  }

  formatMarkdown(text: string): string {
    if (!text) return '';
    let html = text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');
    html = html.replace(/\n/g, '<br/>');
    return html;
  }

  logout() {
    localStorage.removeItem('ksp_officer');
    this.router.navigate(['/login']);
  }

  addSystemGreeting() {
    this.chatHistory.push({
      role: 'assistant',
      content: `Jai Hind, Officer ${this.officerName}. KSP CrimeAI Command Assistant is ready.`,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    });
  }

  sendChatMessage() {
    if (!this.chatInput.trim()) return;
    const query = this.chatInput;
    this.chatHistory.push({
      role: 'user',
      content: query,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    });
    this.chatInput = '';

    this.apiService.chat(query, this.officerBadge, this.officerRole, this.officerLanguage).subscribe(res => {
      if (res.isBlocked || res.error) {
        this.chatHistory.push({
          role: 'assistant',
          content: res.error || 'Access Denied.',
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          isBlocked: true
        });
        return;
      }

      const responseContent = res.response || '';
      let isTableQuery = false;
      let tableData: any[] = [];
      let tableHeaders: string[] = [];

      // Detect markdown tables only
      const lines = responseContent.split('\n');
      const tableLines = lines.filter((line: string) => line.trim().startsWith('|'));
      if (tableLines.length >= 3) {
        const headers = tableLines[0].split('|').map((s: string) => s.trim()).filter((s: string) => s);
        const rows = tableLines.slice(2).map((line: string) => {
          const cells = line.split('|').map((s: string) => s.trim()).filter((_s: string, idx: number) => idx > 0 && idx <= headers.length);
          const obj: any = {};
          headers.forEach((h: string, i: number) => { obj[h] = cells[i] || ''; });
          return obj;
        }).filter((obj: any) => Object.values(obj).some((v: any) => v));

        if (rows.length > 0) {
          isTableQuery = true;
          tableHeaders = headers;
          tableData = rows;
        }
      }

      this.chatHistory.push({
        role: 'assistant',
        content: responseContent,
        isTable: isTableQuery && tableData.length > 0,
        tableData: tableData.length > 0 ? tableData : undefined,
        tableHeaders: tableHeaders.length > 0 ? tableHeaders : undefined,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      });

      this.auditLogs.unshift({
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        log: `Officer queried: "${res.intent || 'general'}"`
      });
      if (this.auditLogs.length > 10) this.auditLogs.pop();
    });
  }

  simulateVoiceQuery() {
    this.isVoiceRecording = true;
    setTimeout(() => {
      this.isVoiceRecording = false;
      this.apiService.transcribeVoice("fakeWavBytesBase64", this.officerLanguage, this.officerBadge).subscribe(res => {
        this.chatInput = res.transcribed_text;
        this.sendChatMessage();
      });
    }, 2000);
  }

  exportChat() {
    this.apiService.exportPdf(this.chatHistory.map(c => ({ role: c.role, content: c.content })), this.officerBadge).subscribe(res => {
      const win = window.open('', '_blank');
      if (win) {
        win.document.write(res.html);
        win.document.close();
        setTimeout(() => { win.print(); }, 500);
      } else {
        alert('Popup blocked! Please allow popups.');
      }
    });
  }

  initMap() {
    if (this.mapKarnataka) { try { this.mapKarnataka.remove(); } catch (e) {} }
    if (this.mapBengaluru) { try { this.mapBengaluru.remove(); } catch (e) {} }

    this.mapKarnataka = L.map(this.mapKarnatakaContainer.nativeElement).setView([14.05, 76.5], 7);
    L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', { maxZoom: 20 }).addTo(this.mapKarnataka);

    this.mapBengaluru = L.map(this.mapBengaluruContainer.nativeElement).setView([12.9307, 77.5847], 12);
    L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', { maxZoom: 20 }).addTo(this.mapBengaluru);

    this.loadHotspots();
    setTimeout(() => { this.initMapCharts(); }, 200);
  }

  initMapCharts() {
    if (this.donutChartInstance) this.donutChartInstance.destroy();
    const donutCtx = this.mapDonutCanvas.nativeElement.getContext('2d');
    this.donutChartInstance = new Chart(donutCtx, {
      type: 'doughnut',
      data: {
        labels: ['Bengaluru', 'Jayanagar', 'Koramangala', 'Mysore', 'Mandya'],
        datasets: [{ data: [45, 25, 18, 12, 10], backgroundColor: ['#eab308', '#caca04', '#f59e0b', '#3b82f6', '#10b981'], borderWidth: 0 }]
      },
      options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'bottom', labels: { color: '#94a3b8', font: { size: 9 } } } } }
    });

    if (this.barChartInstance) this.barChartInstance.destroy();
    const barCtx = this.mapBarCanvas.nativeElement.getContext('2d');
    this.barChartInstance = new Chart(barCtx, {
      type: 'bar',
      data: { labels: ['Theft', 'Breaking', 'Robbery', 'Assault', 'Fraud'], datasets: [{ label: 'Crime Count', data: [120, 90, 45, 30, 65], backgroundColor: '#ca8a04' }] },
      options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { x: { ticks: { color: '#94a3b8', font: { size: 8 } } }, y: { ticks: { color: '#94a3b8', font: { size: 8 } } } } }
    });

    if (this.lineChartInstance) this.lineChartInstance.destroy();
    const lineCtx = this.mapLineCanvas.nativeElement.getContext('2d');
    this.lineChartInstance = new Chart(lineCtx, {
      type: 'line',
      data: { labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], datasets: [{ label: 'Trend Density', data: [40, 55, 45, 80, 95, 110], borderColor: '#eab308', backgroundColor: 'rgba(234,179,8,0.1)', fill: true }] },
      options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { x: { ticks: { color: '#94a3b8', font: { size: 8 } } }, y: { ticks: { color: '#94a3b8', font: { size: 8 } } } } }
    });
  }

  loadHotspots() {
    this.apiService.getHotspots(this.selectedCrimeType).subscribe(res => {
      this.mapLocations = res.data;
      [this.mapKarnataka, this.mapBengaluru].forEach(m => {
        if (!m) return;
        m.eachLayer(layer => { if (layer instanceof L.Circle || layer instanceof L.Marker) m.removeLayer(layer); });
      });

      const groups: { [key: string]: { coords: [number, number]; count: number; items: any[] } } = {};
      this.mapLocations.forEach(loc => {
        const coordsStr = loc.geo_coordinates;
        if (!coordsStr) return;
        const coords = coordsStr.split(',').map((c: string) => parseFloat(c));
        if (coords.length === 2 && !isNaN(coords[0]) && !isNaN(coords[1])) {
          if (!groups[coordsStr]) groups[coordsStr] = { coords: [coords[0], coords[1]], count: 0, items: [] };
          groups[coordsStr].count++;
          groups[coordsStr].items.push(loc);
        }
      });

      Object.keys(groups).forEach(key => {
        const grp = groups[key];
        const isHighDensity = grp.count >= 2;
        const color = isHighDensity ? '#ef4444' : '#10b981';
        if (this.mapKarnataka) L.circle(grp.coords, { color, fillColor: color, fillOpacity: 0.6, radius: 2000 + (grp.count * 500) }).addTo(this.mapKarnataka);
        if (this.mapBengaluru) {
          const circle = L.circle(grp.coords, { color, fillColor: color, fillOpacity: 0.5, radius: 300 + (grp.count * 100) }).addTo(this.mapBengaluru);
          const crimesList = grp.items.map(item => `• ${item.crime_type} (${item.region})`).join('<br/>');
          circle.bindPopup(`<div style="color:#1e293b;font-family:Inter,sans-serif;padding:4px;min-width:160px;"><h4 style="margin:0 0 6px 0;color:${color};font-size:12px;">${isHighDensity ? '⚠️ High Crime Density' : '✅ Low Crime Density'}</h4><p style="font-size:11px;"><strong>Crimes:</strong> ${grp.count}</p><div style="font-size:10px;">${crimesList}</div></div>`);
        }
      });
    });
  }

  initNetworkGraph() {
    const el = this.networkContainer.nativeElement;
    el.innerHTML = '';
    this.apiService.getNetwork(this.offenderSearchId).subscribe(res => {
      this.networkData = res.network.data;
      const nodeMap = new Map<string, any>();
      const links: any[] = [];
      this.networkData.forEach((row: any) => {
        if (!nodeMap.has(row.offender_1_id)) nodeMap.set(row.offender_1_id, { id: row.offender_1_id, name: row.offender_1_name, type: 'gang_member' });
        if (!nodeMap.has(row.offender_2_id)) nodeMap.set(row.offender_2_id, { id: row.offender_2_id, name: row.offender_2_name, type: 'gang_member' });
        links.push({ source: row.offender_1_id, target: row.offender_2_id, label: row.crime_id || '' });
      });
      const nodes: any[] = Array.from(nodeMap.values());
      const width = el.clientWidth || 900;
      const height = el.clientHeight || 550;
      const svg = d3.select(el).append('svg').attr('width', '100%').attr('height', '100%').attr('viewBox', `0 0 ${width} ${height}`).style('background', '#080c14');
      const defs = svg.append('defs');
      const filterRed = defs.append('filter').attr('id', 'glow-red').attr('x', '-50%').attr('y', '-50%').attr('width', '200%').attr('height', '200%');
      filterRed.append('feGaussianBlur').attr('stdDeviation', '8').attr('result', 'coloredBlur');
      const feMergeRed = filterRed.append('feMerge');
      feMergeRed.append('feMergeNode').attr('in', 'coloredBlur');
      feMergeRed.append('feMergeNode').attr('in', 'SourceGraphic');
      defs.append('marker').attr('id', 'arrow-red').attr('viewBox', '0 -5 10 10').attr('refX', 22).attr('refY', 0).attr('markerWidth', 6).attr('markerHeight', 6).attr('orient', 'auto').append('path').attr('d', 'M0,-5L10,0L0,5').attr('fill', '#ef4444');
      const g = svg.append('g');
      const simulation = d3.forceSimulation<any>(nodes).force('link', d3.forceLink<any, any>(links).id((d: any) => d.id).distance(120)).force('charge', d3.forceManyBody().strength(-220)).force('center', d3.forceCenter(width / 2, height / 2));
      const link = g.append('g').selectAll('line').data(links).enter().append('line').attr('stroke', '#ef4444').attr('stroke-width', 2).attr('opacity', 0.7).attr('marker-end', 'url(#arrow-red)');
      const node = g.append('g').selectAll('g').data(nodes).enter().append('g').call(d3.drag<any, any>().on('start', (event: any, d: any) => { if (!event.active) simulation.alphaTarget(0.3).restart(); d.fx = d.x; d.fy = d.y; }).on('drag', (event: any, d: any) => { d.fx = event.x; d.fy = event.y; }).on('end', (event: any, d: any) => { if (!event.active) simulation.alphaTarget(0); d.fx = null; d.fy = null; }));
      node.each(function(d: any) {
        const sel = d3.select(this);
        sel.append('circle').attr('r', 24).attr('fill', 'rgba(239,68,68,0.4)').attr('filter', 'url(#glow-red)');
        sel.append('circle').attr('r', 16).attr('fill', '#991b1b').attr('stroke', '#ef4444').attr('stroke-width', 2);
        sel.append('text').text('👤').attr('x', -6).attr('y', 5).attr('font-size', '12px');
        sel.append('text').text(d.name).attr('x', 0).attr('y', 32).attr('text-anchor', 'middle').attr('fill', '#fef08a').attr('font-size', '10px').attr('font-weight', 'bold');
      });
      simulation.on('tick', () => {
        link.attr('x1', (d: any) => d.source.x).attr('y1', (d: any) => d.source.y).attr('x2', (d: any) => d.target.x).attr('y2', (d: any) => d.target.y);
        node.attr('transform', (d: any) => `translate(${d.x},${d.y})`);
      });
    });
  }

  fetchCaseSummary() {
    this.apiService.getCaseSummary(this.searchCrimeId, this.officerLanguage).subscribe(res => {
      this.caseSummaryText = res.summary;
      this.caseTimeline = [
        { date: '25 May 24', event: 'FIR Registration', details: `FIR #${this.searchCrimeId} registered.`, icon: '📝', officer: this.officerName },
        { date: '29 May 24', event: 'Interrogation', details: 'Interrogation of suspect completed.', icon: '👥', officer: this.officerName },
        { date: '28 May 24', event: 'Evidence Upload', details: 'CCTV Footage uploaded.', icon: '📹', officer: this.officerName },
        { date: '26 May 24', event: 'Evidence Upload', details: 'Fingerprint data uploaded.', icon: '🧬', officer: this.officerName }
      ];
      this.auditLogs.unshift({ time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), log: `Case Summary generated for ${this.searchCrimeId}` });
    });
  }

  initTrendChart() {
    if (this.chartInstance) this.chartInstance.destroy();
    const ctx = this.chartCanvas.nativeElement.getContext('2d');
    this.chartInstance = new Chart(ctx, {
      type: 'line',
      data: {
        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
        datasets: [
          { label: 'Theft & House Breaking', data: [65, 59, 80, 81, 96, 120, 115], borderColor: '#eab308', backgroundColor: 'rgba(234,179,8,0.1)', tension: 0.4, fill: true },
          { label: 'Robbery & Violent Crime', data: [28, 48, 40, 19, 36, 27, 40], borderColor: '#ef4444', backgroundColor: 'rgba(239,68,68,0.1)', tension: 0.4, fill: true }
        ]
      },
      options: {
        responsive: true, maintainAspectRatio: false,
        plugins: { legend: { labels: { color: '#94a3b8', font: { family: 'Inter' } } } },
        scales: { x: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: '#94a3b8' } }, y: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: '#94a3b8' } } }
      }
    });
  }
}